## this is pretty much the same docker-compose file that Danbooru has in the repo, but uses
##   locally built images and bind mounts a configuration file
## honestly following most of their docs/resources should get you enough to get you a basic instance deployed
##
# A Docker Compose file that launches a minimal Danbooru instance. This is
# suitable as a quick demo or for personal use, not for public-facing sites.
#
# This will start a Danbooru instance running on http://localhost.
#
# Usage:
#
#  docker-compose up
#  docker-compose down
#
# References:
#
# * https://docs.docker.com/get-docker/
# * https://docs.docker.com/compose/install/
# * https://docs.docker.com/compose/compose-file/compose-versioning
# * https://docs.docker.com/compose/release-notes

# Version 3.4 is the latest version that is supported by the version of Docker
# Compose shipped with Ubuntu 18.04 LTS (version 1.17.4).
version: "3.4"

services:
  danbooru:
    user: root
    image: danbooru:20210907
    ports:
      - "8080:3000"
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DATABASE_URL=postgresql://danbooru@postgres/danbooru
    volumes:
      - "danbooru-images:/danbooru/public/data"
      - type: bind
        source: /srv/booru/danbooru_local_config.rb
        target: /danbooru/config/danbooru_local_config.rb
    tmpfs:
      - /tmp
    depends_on:
      - postgres
    command: ["bash", "-c", "bin/rails db:setup; bin/rails db:migrate && bin/rails server -b 0.0.0.0"]
    user: root

  cron:
    user: root
    image: danbooru:20210907
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://danbooru@postgres/danbooru
    depends_on:
      - danbooru
    volumes:
      - "danbooru-images:/danbooru/public/data"
      - type: bind
        source: /srv/booru/danbooru_local_config.rb
        target: /danbooru/config/danbooru_local_config.rb
    command: ["bash", "-c", "bin/wait-for-http http://danbooru:3000 5s && bin/rails danbooru:cron"]

  delayed_jobs:
    # We need root to write temp upload files in the images directory (/danbooru/public/data)
    user: root
    image: danbooru:20210907
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://danbooru@postgres/danbooru
    depends_on:
      - danbooru
    volumes:
      # We need access to images so we can add/remove images to IQDB.
      - "danbooru-images:/danbooru/public/data"
      - type: bind
        source: /srv/booru/danbooru_local_config.rb
        target: /danbooru/config/danbooru_local_config.rb
    command: ["bash", "-c", "bin/wait-for-http http://danbooru:3000 5s && bin/delayed_job run"]

  # https://github.com/danbooru/iqdb
  # https://hub.docker.com/repository/docker/evazion/iqdb
  iqdb:
    image: iqdb:20210911
    volumes:
      - "iqdb-data:/iqdb/data"
    command: ["http", "0.0.0.0", "5588", "/iqdb/data/iqdb.sqlite"]

  redis:
    image: redis

  postgres:
    image: danbooru-pgsql:20210907
    environment:
      POSTGRES_USER: danbooru
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "danbooru-data:/var/lib/postgresql/data"

volumes:
  danbooru-images:
    name: danbooru-images
  danbooru-data:
    name: danbooru-data
  iqdb-data:
    name: iqdb-data
